# Generated by Django 5.1.4 on 2025-01-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_remove_article_consigne_article_prix_consigne'),
        ('clients', '0003_insert_type_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('prix_htva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rappel1', models.DateField(blank=True, null=True)),
                ('rappel2', models.DateField(blank=True, null=True)),
                ('rappel3', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('est_comptabilise', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField()),
                ('prix_article_htva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_article_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_facture', to='articles.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='factures.facture')),
            ],
        ),
    ]
