# Generated by Django 5.1.4 on 2025-02-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_facture_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsfacture',
            name='prix_total_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
