# Generated by Django 5.1.4 on 2024-12-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Nom_Entreprise', models.CharField(max_length=200, null=True)),
                ('TVA_Entreprise', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code_Postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pays', models.CharField(max_length=100)),
                ('Code_iso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rue', models.CharField(max_length=200)),
                ('Numero', models.CharField(max_length=15)),
                ('Boite', models.CharField(max_length=15)),
                ('id_CP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.code_postal')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adresse')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('id_Type_Adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.type_adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ville', models.CharField(max_length=100)),
                ('id_Ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pays')),
            ],
        ),
        migrations.AddField(
            model_name='code_postal',
            name='id_Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ville'),
        ),
    ]
