# Generated by Django 5.1.4 on 2025-01-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nom_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('tva_entreprise', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code_Postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('code_iso', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('boite', models.CharField(blank=True, max_length=10)),
                ('clients', models.ManyToManyField(related_name='adresses', to='clients.client')),
                ('code_postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.code_postal')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(max_length=50)),
                ('adresses', models.ManyToManyField(related_name='type_adresses', to='clients.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.pays')),
            ],
        ),
        migrations.AddField(
            model_name='code_postal',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ville'),
        ),
    ]
