# Generated by Django 5.1.4 on 2024-12-30 17:06

from django.db import migrations

def addTypeAdresse(apps, schema_editor):
    Type_Adresse = apps.get_model('clients', 'Type_Adresse')

    Type_Adresse.objects.create(type_adresse="Facturation")
    Type_Adresse.objects.create(type_adresse="Livraison")


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addTypeAdresse)
    ]
