# Generated by Django 5.1.4 on 2025-01-17 12:04

from django.db import migrations

def addType_Adresse(apps, schema_editor):
    Type_Adresse = apps.get_model('clients', 'Type_Adresse')
    Type_Adresse.objects.create(type_adresse="Livraison")
    Type_Adresse.objects.create(type_adresse="Facturation")

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_insert_pays'),
    ]

    operations = [
        migrations.RunPython(addType_Adresse)
    ]